<?xml version='1.0'?>

<robot name="atom" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="robot_name" value="iot_robot" />
	<xacro:property name="robot_chassis_mass" value="15"/>
	<xacro:property name="robot_chassis_length" value="0.2"/>
	<xacro:property name="robot_chassis_radius" value="0.25"/>
	<xacro:property name="robot_caster_wheel_radius" value="0.05"/>
	<xacro:property name="robot_caster_wheel_radius_collision" value="0.0499"/>

	<xacro:property name="robot_wheel_mass" value="5"/>
	<xacro:property name="robot_wheel_length" value="0.02"/>
	<xacro:property name="robot_wheel_radius" value="0.075"/>
	<xacro:property name="robot_width" value="0.3"/>
	<xacro:property name="robot_length" value="0.5"/>

	<xacro:property name="camera_mass" value="0.1"/>
	<xacro:property name="hokoyu_mass" value="1e-5"/>

	<link name="base_footprint"></link>

	<link name="base_link">
		<pose>0 0 0 0 0 0</pose>

		<inertial>
			<mass value="${robot_chassis_mass}"/>
      		<origin xyz="0.0 0 0" rpy=" 0 0 0"/>

      		<inertia ixx="0.147116667" ixy="0" ixz="0" iyy="0.334951167" iyz="0" izz="0.3978345"/></inertial>

		<collision name="collision">
			<origin xyz="0 0 0.0" rpy=" 0 0 0"/>
			<geometry>
				<box size="${robot_length} ${robot_width} 0.05"/>
			</geometry>
		</collision>

		<visual name="chassis_visual">
			<origin xyz="0 0 0.0" rpy=" 0 0 0"/>
			<geometry>
				<box size="${robot_length} ${robot_width} 0.05"/>
			</geometry>
		</visual>

	</link>

	<!-- Right Wheel Back -->
	<link name="right_wheel_back">
		<inertial>
			<mass value="${robot_wheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<inertia
				ixx="0.1" ixy="0.0" ixz="0.0"
				iyy="0.1" iyz="0.0"
				izz="0.1"
			/>
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</collision>

	</link>

	<!-- Right Wheel Front-->
	<link name="right_wheel_front">
		<inertial>
			<mass value="${robot_wheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<inertia
				ixx="0.1" ixy="0.0" ixz="0.0"
				iyy="0.1" iyz="0.0"
				izz="0.1"
			/>
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</collision>

	</link>



	<!-- Left wheel Back-->
	<link name="left_wheel_back">
		<inertial>
			<mass value="${robot_wheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<inertia
				ixx="0.1" ixy="0.0" ixz="0.0"
				iyy="0.1" iyz="0.0"
				izz="0.1"
			/>
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</collision>

	</link>

	<!-- Left wheel Front-->
	<link name="left_wheel_front">
		<inertial>
			<mass value="${robot_wheel_mass}"/>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<inertia
				ixx="0.1" ixy="0.0" ixz="0.0"
				iyy="0.1" iyz="0.0"
				izz="0.1"
			/>
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
			<geometry>
				<cylinder radius="${robot_wheel_radius}" length="${robot_wheel_length}"/>
			</geometry>
		</collision>

	</link>

	<!-- Camera -->
	<!-- <link name="camera">
		<inertial>
			<mass value="${camera_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia
		        ixx="1e-6" ixy="0.0" ixz="0.0"
		        iyy="1e-6" iyz="0.0"
		        izz="1e-6"
		      />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</collision>
	</link> -->

	<link name="camera_link">
	    <collision>
	      <origin xyz="0.02 0 0" rpy="0 0 0"/>
	      <geometry>
	        <box size="0.001 0.001 0.001"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0.01 0 0" rpy="1.5707 0 1.5707"/>
	      <geometry>
	         <mesh filename="package://robot_description/meshes/NAVRS.STL" />
	      </geometry>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
	    </inertial>
	</link>

  	<link name="camera_rgb_frame"></link>

    <link name="camera_depth_frame"> </link>

	<link name="ultrasonic_left">
	    <collision>
	      <origin xyz="0.03 0 0" rpy="1.57 0 3.14"/>
	      <geometry>
	        <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0.03 0 0" rpy="1.57 0 3.14"/>
	      <geometry>
	         <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
	    </inertial>
	</link>

	<link name="ultrasonic_left_range"> </link>

	<link name="ultrasonic_right">
	    <collision>
	      <origin xyz="-0.03 0 0" rpy="1.57 0 0"/>
	      <geometry>
	        <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="-0.03 0 0" rpy="1.57 0 0"/>
	      <geometry>
	         <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
	    </inertial>
	</link>

	<link name="ultrasonic_right_range"> </link>

	<link name="ultrasonic_back">
	    <collision>
	      <origin xyz="0 0.03 0" rpy="1.57 0 -1.57"/>
	      <geometry>
	        <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0.03 0" rpy="1.57 0 -1.57"/>
	      <geometry>
	         <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/ULTRASONIC_SENSOR.STL" />
	      </geometry>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
	    </inertial>
	</link>

	<!-- Dummy link to get axis is right direction -->
	<link name="ultrasonic_back_range"> </link>

	<link name="rpi">
	    <collision>
	      <origin xyz="-0.9 0.75 0.9" rpy="0 0 0"/>
	      <geometry>
	        <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/RPI.stl" />
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="-0.9 0.75 0.9" rpy="0 0 0"/>
	      <geometry>
	         <mesh scale="0.001 0.001 0.001" filename="package://robot_description/meshes/RPI.stl" />
	      </geometry>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
	    </inertial>
	</link>

	<!-- Right Wheel Joint Back-->
	<joint type="continuous" name="right_wheel_hinge_back">
	    <origin xyz="-${robot_width/2 - 0.025} -${robot_width/2 + robot_wheel_length/2 +0.001} 0" rpy="0 0 0" />
	    <parent link="base_link"/>
	    <child link="right_wheel_back" />
	    <axis xyz="0 1 0" rpy="0 0 0" />
	    <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
	</joint>

	<!-- Right Wheel Joint Front-->
	<joint type="continuous" name="right_wheel_hinge_front">
	    <origin xyz="${robot_width/2 - 0.025}  -${robot_width/2 + robot_wheel_length/2 +0.001} 0" rpy="0 0 0" />
	    <parent link="base_link"/>
	    <child link="right_wheel_front" />
	    <axis xyz="0 1 0" rpy="0 0 0" />
	    <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
	</joint>


	<!-- Left Wheel Joint Back-->
	<joint type="continuous" name="left_wheel_hinge_back">
	    <origin xyz="-${robot_width/2 - 0.025} ${robot_width/2 + robot_wheel_length/2 +0.001} 0" rpy="0 0 0" />
	    <parent link="base_link"/>
	    <child link="left_wheel_back" />
	    <axis xyz="0 1 0" rpy="0 0 0" />
	    <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
	</joint>

	<!-- Left Wheel Joint Front-->
	<joint type="continuous" name="left_wheel_hinge_front">
	    <origin xyz="${robot_width/2 - 0.025}  ${robot_width/2 + robot_wheel_length/2 +0.001} 0" rpy="0 0 0" />
	    <parent link="base_link"/>
	    <child link="left_wheel_front" />
	    <axis xyz="0 1 0" rpy="0 0 0" />
	    <limit effort="10000" velocity="1000" />
	    <dynamics damping="1.0" friction="1.0" />
	</joint>

	<!-- Camera Joint -->
	<!-- <joint name="camera_joint" type="fixed">
		<origin xyz="0.26 0 0" rpy="0 0 0" />
		<parent link="base_link"/>
		<child link="camera" />
		<axis xyz="0 1 0"/>
	</joint> -->

 	<joint name="intelrealsense" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0.25 0 0.05" rpy="0 0 0"/>
 	   <parent link="base_link"/>
 	   <child link="camera_link"/>
 	 </joint>

  	<joint name="camera_optical_joint" type="fixed">
  	  <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
  	  <parent link="camera_link"/>
  	  <child link="camera_rgb_frame"/>
  	</joint>

  	<joint name="camera_depth_joint" type="fixed">
  	  <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
  	  <parent link="camera_link"/>
  	  <child link="camera_depth_frame"/>
  	</joint>

	<joint name="robot_footprint_joint" type="fixed">
		<origin xyz="0 0 0.1" rpy="0 0 0" />
		<parent link="base_footprint"/>
		<child link="base_link" />
	</joint>

 	<joint name="ultrasonic_left_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0 0.14 0.03" rpy="0 0 0"/>
 	   <parent link="base_link"/>
 	   <child link="ultrasonic_left"/>
 	 </joint>

	<joint name="ultrasonic_left_range_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0.02 0 0" rpy="0 0 1.57"/>
 	   <parent link="ultrasonic_left"/>
 	   <child link="ultrasonic_left_range"/>
 	 </joint>

 	<joint name="ultrasonic_right_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0 -0.14 0.03" rpy="0 0 0"/>
 	   <parent link="base_link"/>
 	   <child link="ultrasonic_right"/>
 	 </joint>

	<joint name="ultrasonic_right_range_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0.02 0 0" rpy="0 0 -1.57"/>
 	   <parent link="ultrasonic_right"/>
 	   <child link="ultrasonic_right_range"/>
 	 </joint>

 	<joint name="ultrasonic_back_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="-0.25 0 0.03" rpy="0 0 0"/>
 	   <parent link="base_link"/>
 	   <child link="ultrasonic_back"/>
 	 </joint>

	<joint name="ultrasonic_back_range_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0.02 0 0" rpy="0 0 3.14"/>
 	   <parent link="ultrasonic_back"/>
 	   <child link="ultrasonic_back_range"/>
 	 </joint>

 	<joint name="rpi_joint" type="fixed">
 	   <axis xyz="0 0 0" />
 	   <origin xyz="0 0 0.03" rpy="0 0 0"/>
 	   <parent link="base_link"/>
 	   <child link="rpi"/>
 	 </joint>

	<!-- Color of bot -->
	<gazebo reference="left_wheel_front">
		<material>Gazebo/Black</material>
		<kp>1000000.0</kp> <!-- kp and kd for rubber -->
		<kd>100.0</kd>
		<mu1>1.0</mu1>
		<mu2>1.0</mu2>
		<maxVel>1.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>

	<gazebo reference="left_wheel_back">
		<material>Gazebo/Black</material>
		<kp>1000000.0</kp> <!-- kp and kd for rubber -->
		<kd>100.0</kd>
		<mu1>1.0</mu1>
		<mu2>1.0</mu2>
		<maxVel>1.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>

	<gazebo reference="right_wheel_front">
		<material>Gazebo/Black</material>
		<kp>1000000.0</kp> <!-- kp and kd for rubber -->
		<kd>100.0</kd>
		<mu1>1.0</mu1>
		<mu2>1.0</mu2>
		<maxVel>1.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>
	<gazebo reference="right_wheel_back">
		<material>Gazebo/Black</material>
		<kp>1000000.0</kp> <!-- kp and kd for rubber -->
		<kd>100.0</kd>
		<mu1>1.0</mu1>
		<mu2>1.0</mu2>
		<maxVel>1.0</maxVel>
		<minDepth>0.00</minDepth>
	</gazebo>


	<gazebo reference="camera_link">
		<material>Gazebo/Blue</material>
	</gazebo>

	<gazebo reference="ultrasonic_left">
		<material>Gazebo/Blue</material>
	</gazebo>

	<gazebo reference="ultrasonic_right">
		<material>Gazebo/Blue</material>
	</gazebo>

	<gazebo reference="rpi">
		<material>Gazebo/Green</material>
	</gazebo>

	<gazebo reference="ultrasonic_back">
		<material>Gazebo/Blue</material>
	</gazebo>

	<gazebo reference="base_footprint">
		<material>Gazebo/Blue</material>
	</gazebo>
	<xacro:include filename="$(find robot_description)/urdf/robot.gazebo" />
</robot>